os: osx
cache: 
 bundler: true
 directories:
     - /home/travis/.rvm/
before_script:
 - pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
 - bin/rails db:create
 - bin/rails db:migrate
language: ruby
rvm:
 - 2.5.0